"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class JobSubmission(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    TIMEOUT_MS_FIELD_NUMBER: builtins.int
    WORKFLOW_TYPE_FIELD_NUMBER: builtins.int
    ESDL_FIELD_NUMBER: builtins.int
    PARAMS_DICT_FIELD_NUMBER: builtins.int
    JOB_REFERENCE_FIELD_NUMBER: builtins.int
    uuid: builtins.str
    timeout_ms: builtins.int
    workflow_type: builtins.str
    esdl: builtins.str
    """Raw XML string"""
    @property
    def params_dict(self) -> google.protobuf.struct_pb2.Struct: ...
    job_reference: builtins.str
    def __init__(
        self,
        *,
        uuid: builtins.str = ...,
        timeout_ms: builtins.int | None = ...,
        workflow_type: builtins.str = ...,
        esdl: builtins.str = ...,
        params_dict: google.protobuf.struct_pb2.Struct | None = ...,
        job_reference: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_job_reference", b"_job_reference", "_timeout_ms", b"_timeout_ms", "job_reference", b"job_reference", "params_dict", b"params_dict", "timeout_ms", b"timeout_ms"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_job_reference", b"_job_reference", "_timeout_ms", b"_timeout_ms", "esdl", b"esdl", "job_reference", b"job_reference", "params_dict", b"params_dict", "timeout_ms", b"timeout_ms", "uuid", b"uuid", "workflow_type", b"workflow_type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_job_reference", b"_job_reference"]) -> typing_extensions.Literal["job_reference"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_timeout_ms", b"_timeout_ms"]) -> typing_extensions.Literal["timeout_ms"] | None: ...

global___JobSubmission = JobSubmission

@typing_extensions.final
class JobResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ResultType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ResultTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[JobResult._ResultType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SUCCEEDED: JobResult._ResultType.ValueType  # 0
        TIMEOUT: JobResult._ResultType.ValueType  # 1
        ERROR: JobResult._ResultType.ValueType  # 2
        CANCELLED: JobResult._ResultType.ValueType  # 3

    class ResultType(_ResultType, metaclass=_ResultTypeEnumTypeWrapper): ...
    SUCCEEDED: JobResult.ResultType.ValueType  # 0
    TIMEOUT: JobResult.ResultType.ValueType  # 1
    ERROR: JobResult.ResultType.ValueType  # 2
    CANCELLED: JobResult.ResultType.ValueType  # 3

    UUID_FIELD_NUMBER: builtins.int
    RESULT_TYPE_FIELD_NUMBER: builtins.int
    OUTPUT_ESDL_FIELD_NUMBER: builtins.int
    LOGS_FIELD_NUMBER: builtins.int
    ESDL_MESSAGES_FIELD_NUMBER: builtins.int
    uuid: builtins.str
    result_type: global___JobResult.ResultType.ValueType
    output_esdl: builtins.str
    """Raw XML string"""
    logs: builtins.str
    @property
    def esdl_messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EsdlMessage]: ...
    def __init__(
        self,
        *,
        uuid: builtins.str = ...,
        result_type: global___JobResult.ResultType.ValueType = ...,
        output_esdl: builtins.str | None = ...,
        logs: builtins.str = ...,
        esdl_messages: collections.abc.Iterable[global___EsdlMessage] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_output_esdl", b"_output_esdl", "output_esdl", b"output_esdl"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_output_esdl", b"_output_esdl", "esdl_messages", b"esdl_messages", "logs", b"logs", "output_esdl", b"output_esdl", "result_type", b"result_type", "uuid", b"uuid"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_output_esdl", b"_output_esdl"]) -> typing_extensions.Literal["output_esdl"] | None: ...

global___JobResult = JobResult

@typing_extensions.final
class EsdlMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Severity:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SeverityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EsdlMessage._Severity.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DEBUG: EsdlMessage._Severity.ValueType  # 0
        INFO: EsdlMessage._Severity.ValueType  # 1
        WARNING: EsdlMessage._Severity.ValueType  # 2
        ERROR: EsdlMessage._Severity.ValueType  # 3

    class Severity(_Severity, metaclass=_SeverityEnumTypeWrapper): ...
    DEBUG: EsdlMessage.Severity.ValueType  # 0
    INFO: EsdlMessage.Severity.ValueType  # 1
    WARNING: EsdlMessage.Severity.ValueType  # 2
    ERROR: EsdlMessage.Severity.ValueType  # 3

    TECHNICAL_MESSAGE_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    ESDL_OBJECT_ID_FIELD_NUMBER: builtins.int
    technical_message: builtins.str
    severity: global___EsdlMessage.Severity.ValueType
    esdl_object_id: builtins.str
    """can be omitted for general energy system messages"""
    def __init__(
        self,
        *,
        technical_message: builtins.str = ...,
        severity: global___EsdlMessage.Severity.ValueType = ...,
        esdl_object_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["esdl_object_id", b"esdl_object_id", "severity", b"severity", "technical_message", b"technical_message"]) -> None: ...

global___EsdlMessage = EsdlMessage

@typing_extensions.final
class JobProgressUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    uuid: builtins.str
    progress: builtins.float
    message: builtins.str
    def __init__(
        self,
        *,
        uuid: builtins.str = ...,
        progress: builtins.float = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message", "progress", b"progress", "uuid", b"uuid"]) -> None: ...

global___JobProgressUpdate = JobProgressUpdate

@typing_extensions.final
class JobStatusUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _JobStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _JobStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[JobStatusUpdate._JobStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        REGISTERED: JobStatusUpdate._JobStatus.ValueType  # 0
        ENQUEUED: JobStatusUpdate._JobStatus.ValueType  # 1
        RUNNING: JobStatusUpdate._JobStatus.ValueType  # 2
        FINISHED: JobStatusUpdate._JobStatus.ValueType  # 3
        CANCELLED: JobStatusUpdate._JobStatus.ValueType  # 4

    class JobStatus(_JobStatus, metaclass=_JobStatusEnumTypeWrapper): ...
    REGISTERED: JobStatusUpdate.JobStatus.ValueType  # 0
    ENQUEUED: JobStatusUpdate.JobStatus.ValueType  # 1
    RUNNING: JobStatusUpdate.JobStatus.ValueType  # 2
    FINISHED: JobStatusUpdate.JobStatus.ValueType  # 3
    CANCELLED: JobStatusUpdate.JobStatus.ValueType  # 4

    UUID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    uuid: builtins.str
    status: global___JobStatusUpdate.JobStatus.ValueType
    def __init__(
        self,
        *,
        uuid: builtins.str = ...,
        status: global___JobStatusUpdate.JobStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["status", b"status", "uuid", b"uuid"]) -> None: ...

global___JobStatusUpdate = JobStatusUpdate

@typing_extensions.final
class JobCancel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    uuid: builtins.str
    def __init__(
        self,
        *,
        uuid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uuid", b"uuid"]) -> None: ...

global___JobCancel = JobCancel
