"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class StringEnum(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    key_name: builtins.str
    display_name: builtins.str
    def __init__(
        self,
        *,
        key_name: builtins.str = ...,
        display_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["display_name", b"display_name", "key_name", b"key_name"]) -> None: ...

global___StringEnum = StringEnum

@typing_extensions.final
class StringParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULT_FIELD_NUMBER: builtins.int
    ENUM_OPTIONS_FIELD_NUMBER: builtins.int
    default: builtins.str
    @property
    def enum_options(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StringEnum]: ...
    def __init__(
        self,
        *,
        default: builtins.str | None = ...,
        enum_options: collections.abc.Iterable[global___StringEnum] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_default", b"_default", "default", b"default"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_default", b"_default", "default", b"default", "enum_options", b"enum_options"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_default", b"_default"]) -> typing_extensions.Literal["default"] | None: ...

global___StringParameter = StringParameter

@typing_extensions.final
class BooleanParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULT_FIELD_NUMBER: builtins.int
    default: builtins.bool
    def __init__(
        self,
        *,
        default: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_default", b"_default", "default", b"default"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_default", b"_default", "default", b"default"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_default", b"_default"]) -> typing_extensions.Literal["default"] | None: ...

global___BooleanParameter = BooleanParameter

@typing_extensions.final
class IntegerParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULT_FIELD_NUMBER: builtins.int
    MINIMUM_FIELD_NUMBER: builtins.int
    MAXIMUM_FIELD_NUMBER: builtins.int
    default: builtins.int
    minimum: builtins.int
    maximum: builtins.int
    def __init__(
        self,
        *,
        default: builtins.int | None = ...,
        minimum: builtins.int | None = ...,
        maximum: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_default", b"_default", "_maximum", b"_maximum", "_minimum", b"_minimum", "default", b"default", "maximum", b"maximum", "minimum", b"minimum"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_default", b"_default", "_maximum", b"_maximum", "_minimum", b"_minimum", "default", b"default", "maximum", b"maximum", "minimum", b"minimum"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_default", b"_default"]) -> typing_extensions.Literal["default"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_maximum", b"_maximum"]) -> typing_extensions.Literal["maximum"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_minimum", b"_minimum"]) -> typing_extensions.Literal["minimum"] | None: ...

global___IntegerParameter = IntegerParameter

@typing_extensions.final
class FloatParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULT_FIELD_NUMBER: builtins.int
    MINIMUM_FIELD_NUMBER: builtins.int
    MAXIMUM_FIELD_NUMBER: builtins.int
    default: builtins.float
    minimum: builtins.float
    maximum: builtins.float
    def __init__(
        self,
        *,
        default: builtins.float | None = ...,
        minimum: builtins.float | None = ...,
        maximum: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_default", b"_default", "_maximum", b"_maximum", "_minimum", b"_minimum", "default", b"default", "maximum", b"maximum", "minimum", b"minimum"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_default", b"_default", "_maximum", b"_maximum", "_minimum", b"_minimum", "default", b"default", "maximum", b"maximum", "minimum", b"minimum"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_default", b"_default"]) -> typing_extensions.Literal["default"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_maximum", b"_maximum"]) -> typing_extensions.Literal["maximum"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_minimum", b"_minimum"]) -> typing_extensions.Literal["minimum"] | None: ...

global___FloatParameter = FloatParameter

@typing_extensions.final
class DateTimeParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULT_FIELD_NUMBER: builtins.int
    default: builtins.str
    def __init__(
        self,
        *,
        default: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_default", b"_default", "default", b"default"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_default", b"_default", "default", b"default"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_default", b"_default"]) -> typing_extensions.Literal["default"] | None: ...

global___DateTimeParameter = DateTimeParameter

@typing_extensions.final
class DurationParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULT_FIELD_NUMBER: builtins.int
    default: builtins.str
    def __init__(
        self,
        *,
        default: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_default", b"_default", "default", b"default"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_default", b"_default", "default", b"default"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_default", b"_default"]) -> typing_extensions.Literal["default"] | None: ...

global___DurationParameter = DurationParameter

@typing_extensions.final
class WorkflowParameter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_NAME_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    STRING_PARAMETER_FIELD_NUMBER: builtins.int
    BOOLEAN_PARAMETER_FIELD_NUMBER: builtins.int
    INTEGER_PARAMETER_FIELD_NUMBER: builtins.int
    FLOAT_PARAMETER_FIELD_NUMBER: builtins.int
    DATETIME_PARAMETER_FIELD_NUMBER: builtins.int
    DURATION_PARAMETER_FIELD_NUMBER: builtins.int
    key_name: builtins.str
    title: builtins.str
    description: builtins.str
    @property
    def string_parameter(self) -> global___StringParameter: ...
    @property
    def boolean_parameter(self) -> global___BooleanParameter: ...
    @property
    def integer_parameter(self) -> global___IntegerParameter: ...
    @property
    def float_parameter(self) -> global___FloatParameter: ...
    @property
    def datetime_parameter(self) -> global___DateTimeParameter: ...
    @property
    def duration_parameter(self) -> global___DurationParameter: ...
    def __init__(
        self,
        *,
        key_name: builtins.str = ...,
        title: builtins.str | None = ...,
        description: builtins.str | None = ...,
        string_parameter: global___StringParameter | None = ...,
        boolean_parameter: global___BooleanParameter | None = ...,
        integer_parameter: global___IntegerParameter | None = ...,
        float_parameter: global___FloatParameter | None = ...,
        datetime_parameter: global___DateTimeParameter | None = ...,
        duration_parameter: global___DurationParameter | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_description", b"_description", "_title", b"_title", "boolean_parameter", b"boolean_parameter", "datetime_parameter", b"datetime_parameter", "description", b"description", "duration_parameter", b"duration_parameter", "float_parameter", b"float_parameter", "integer_parameter", b"integer_parameter", "parameter_type", b"parameter_type", "string_parameter", b"string_parameter", "title", b"title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_description", b"_description", "_title", b"_title", "boolean_parameter", b"boolean_parameter", "datetime_parameter", b"datetime_parameter", "description", b"description", "duration_parameter", b"duration_parameter", "float_parameter", b"float_parameter", "integer_parameter", b"integer_parameter", "key_name", b"key_name", "parameter_type", b"parameter_type", "string_parameter", b"string_parameter", "title", b"title"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_description", b"_description"]) -> typing_extensions.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_title", b"_title"]) -> typing_extensions.Literal["title"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["parameter_type", b"parameter_type"]) -> typing_extensions.Literal["string_parameter", "boolean_parameter", "integer_parameter", "float_parameter", "datetime_parameter", "duration_parameter"] | None: ...

global___WorkflowParameter = WorkflowParameter

@typing_extensions.final
class Workflow(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_NAME_FIELD_NUMBER: builtins.int
    TYPE_DESCRIPTION_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    type_name: builtins.str
    type_description: builtins.str
    @property
    def parameters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WorkflowParameter]: ...
    def __init__(
        self,
        *,
        type_name: builtins.str = ...,
        type_description: builtins.str = ...,
        parameters: collections.abc.Iterable[global___WorkflowParameter] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "type_description", b"type_description", "type_name", b"type_name"]) -> None: ...

global___Workflow = Workflow

@typing_extensions.final
class AvailableWorkflows(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKFLOWS_FIELD_NUMBER: builtins.int
    @property
    def workflows(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Workflow]: ...
    def __init__(
        self,
        *,
        workflows: collections.abc.Iterable[global___Workflow] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["workflows", b"workflows"]) -> None: ...

global___AvailableWorkflows = AvailableWorkflows

@typing_extensions.final
class RequestAvailableWorkflows(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RequestAvailableWorkflows = RequestAvailableWorkflows
