"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import omotes_sdk_protocol.job_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TaskResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ResultType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ResultTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TaskResult._ResultType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SUCCEEDED: TaskResult._ResultType.ValueType  # 0
        ERROR: TaskResult._ResultType.ValueType  # 1

    class ResultType(_ResultType, metaclass=_ResultTypeEnumTypeWrapper): ...
    SUCCEEDED: TaskResult.ResultType.ValueType  # 0
    ERROR: TaskResult.ResultType.ValueType  # 1

    JOB_ID_FIELD_NUMBER: builtins.int
    CELERY_TASK_ID_FIELD_NUMBER: builtins.int
    CELERY_TASK_TYPE_FIELD_NUMBER: builtins.int
    RESULT_TYPE_FIELD_NUMBER: builtins.int
    OUTPUT_ESDL_FIELD_NUMBER: builtins.int
    LOGS_FIELD_NUMBER: builtins.int
    ESDL_MESSAGES_FIELD_NUMBER: builtins.int
    job_id: builtins.str
    celery_task_id: builtins.str
    celery_task_type: builtins.str
    result_type: global___TaskResult.ResultType.ValueType
    output_esdl: builtins.str
    logs: builtins.str
    @property
    def esdl_messages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[omotes_sdk_protocol.job_pb2.EsdlMessage]: ...
    def __init__(
        self,
        *,
        job_id: builtins.str = ...,
        celery_task_id: builtins.str = ...,
        celery_task_type: builtins.str = ...,
        result_type: global___TaskResult.ResultType.ValueType = ...,
        output_esdl: builtins.str | None = ...,
        logs: builtins.str = ...,
        esdl_messages: collections.abc.Iterable[omotes_sdk_protocol.job_pb2.EsdlMessage] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_output_esdl", b"_output_esdl", "output_esdl", b"output_esdl"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_output_esdl", b"_output_esdl", "celery_task_id", b"celery_task_id", "celery_task_type", b"celery_task_type", "esdl_messages", b"esdl_messages", "job_id", b"job_id", "logs", b"logs", "output_esdl", b"output_esdl", "result_type", b"result_type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_output_esdl", b"_output_esdl"]) -> typing_extensions.Literal["output_esdl"] | None: ...

global___TaskResult = TaskResult

@typing_extensions.final
class TaskProgressUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _ProgressStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ProgressStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TaskProgressUpdate._ProgressStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        START: TaskProgressUpdate._ProgressStatus.ValueType  # 0

    class ProgressStatus(_ProgressStatus, metaclass=_ProgressStatusEnumTypeWrapper): ...
    START: TaskProgressUpdate.ProgressStatus.ValueType  # 0

    JOB_ID_FIELD_NUMBER: builtins.int
    CELERY_TASK_ID_FIELD_NUMBER: builtins.int
    CELERY_TASK_TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    job_id: builtins.str
    celery_task_id: builtins.str
    celery_task_type: builtins.str
    status: global___TaskProgressUpdate.ProgressStatus.ValueType
    progress: builtins.float
    message: builtins.str
    def __init__(
        self,
        *,
        job_id: builtins.str = ...,
        celery_task_id: builtins.str = ...,
        celery_task_type: builtins.str = ...,
        status: global___TaskProgressUpdate.ProgressStatus.ValueType = ...,
        progress: builtins.float = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["progress", b"progress", "progress_type", b"progress_type", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["celery_task_id", b"celery_task_id", "celery_task_type", b"celery_task_type", "job_id", b"job_id", "message", b"message", "progress", b"progress", "progress_type", b"progress_type", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["progress_type", b"progress_type"]) -> typing_extensions.Literal["status", "progress"] | None: ...

global___TaskProgressUpdate = TaskProgressUpdate
